name: Firestore Daily Backup
on:
  schedule:
    - cron: '0 3 * * *' # Executa todo dia às 03:00 UTC
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Firestore export
        run: |
          DATE=$(date +%Y-%m-%d)
          gcloud firestore export gs://SEU_BUCKET/backup-$DATE
